FROM python:3.9

WORKDIR /API

COPY ./requirements.txt /API/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /API/requirements.txt

COPY ./app /API/app

EXPOSE 8000

CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
